export const WEEKLY = 'weekly'
export const FORTNIGHTLY = 'fortnightly'
export const MONTHLY = 'monthly'
export const ANNUALLY = 'annually'

export const YEAR = 'year'
export const YEARS = 'years'
export const MONTH = 'month'
export const MONTHS = 'months'
export const DAY = 'day'
export const DAYS = 'days'
